language: go
sudo: false

go:
  - "1.12"

env:
  global:
    - VERSION=$(cat VERSION)

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
#install: true


# email me the results of the test runs.
notifications:
  email: true

before_install:
#  - find "${GOPATH%%:*}" -name '*.a' -delete
#  - rm -rf "${GOPATH%%:*}/src/golang.org"
#  - rm -rf "${GOPATH%%:*}/src/github.com"
  - cd
  - go get -u -v golang.org/x/crypto/bcrypt
  - go get -u -v github.com/urfave/negroni
  - go get -u -v github.com/gorilla/mux
  - go get -u -v github.com/mattn/go-sqlite3
  - go get -u -v github.com/spf13/viper
  - go get -u -v github.com/jinzhu/gorm
  - go get -u -v github.com/spf13/cobra
  - go get -u -v github.com/satori/go.uuid
  - go get -u -v github.com/olekukonko/tablewriter
  - go get -u -v github.com/beevik/etree
  - go get -u -v github.com/jinzhu/now
  - go get -u -v github.com/pkg/errors
  - go get -u -v github.com/Jeffail/gabs
  - go get -u -v github.com/vjeantet/jodaTime
  - go get -u -v github.com/sirupsen/logrus

# Anything in before_script that returns a nonzero exit code will flunk the
# build and immediately stop. It's sorta like having set -e enabled in bash.
# Make sure golangci-lint is vendored by running
#   dep ensure -add github.com/golangci/golangci-lint/cmd/golangci-lint
# ...and adding this to your Gopkg.toml file.
#   required = ["github.com/golangci/golangci-lint/cmd/golangci-lint"]
#
# before_script:
# - go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint

install:
  - go get -u -v github.com/mozillazg/request

script:
  - cd $HOME/gopath/src/github.com/swordlordcodingcrew/fennel
  - mkdir build
# as long as the vendor folder is empty, remove it from the config
#  - GOPATH="$HOME/gopath/src/github.com/swordlordcodingcrew/fennel:$HOME/gopath/src/github.com/swordlordcodingcrew/fennel/vendor:/home/travis/gopath"
  - GOPATH="$HOME/gopath/src/github.com/swordlordcodingcrew/fennel:/home/travis/gopath"
  - go build -o build/fenneld-v$VERSION -gcflags "all=-N -l" swordlord.com/fenneld
  - go build -o build/fennelcli-v$VERSION -gcflags "all=-N -l" swordlord.com/fennelcli
#  - make
#  go test -v swordlord.com/fenneld

# With this configuration the build itself runs for every commit and PR
# (which is nice, because we see if everything compiles fine), but the
# deployment only happens when we actually push a tag as well containing
# the version number of the new release.
#
# deploy:
#   provider: releases
#   skip_cleanup: true # Important, otherwise the build output would be purged.
#   api_key:
#     secure: lFGBaF...SJ1lDPDICY=
#   file: bin/myawesomeapp
#   on:
#     repo: account/myawesomeproject
#     tags: true # The deployment happens only if the commit has a tag.

deploy:
  provider: releases
  file:
    - build/fenneld-v$VERSION
    - build/fennelcli-v$VERSION
  api_key:
    secure: NS2Fw2BHbNyWcFxc+tNcMMeNj1BBHYCp5iyx45biOWSepWNl3ZJkJGoGtpRUXNIjkNjjb2fRkz6yCmXdsHXEWMNZu4CpbXR1DZXswXUjtemk0DgzyHMaPWZsIV5eMfcEfzkhLqTbQsYVXeYjo9J1N65CXtHbB0GbTcDm0iMo+5EGXiRT150x4q8Mj4HywShW0arRntH+TdJidKmLpqig/sgp+4tH0rf9ld5XPatwPtDdLlNGYCuii3tiogN+hcd99JYLt10wHi10BXV4i/QRwnCQ/Qw0xctXv+JwCaqrq4NAVXQ+p+n0QTBUTLIsddN8GXT1igMjglNtHQvuiQGnJJga2hBxSQoYfLfw5EHquiKCvS/7IGKaTNODqMHNJxihOYjKgyVjXL7xOi+x3+9enPOWnRargNbztD7XWe+kZjOW9Ab8ea9O31PKWVhPwszwSbDxXxX+o/Cvy5Hs42dIaCykRDUwSCiqphJtHhyxOWOVRW54E3ekvgwRfpXXDJF1H0/SdZr3InUFkLpa/gnv1UC2E+e3yeUa3QKyoYJzb5YdWBlYYmu/YYN5LJXjUmTGwIJQULbZHeTlFigskI1kEmupYpqFnrxY1NBov4rAyS/Vt5wcGTEnPqMf/fgjLCbigCROxuxiFtsplF1K/1TdkXlqgev/9Wzm9zx1ucz3pPA=
  skip_cleanup: true
  on:
    tags: false
